name: Chanty Deployment
on:
  push:
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: NodeJS ${{matrix.node-version}}
      uses: actions/setup-node@v2
      with:
        node-version: ${{matrix.node-version}}
    - run: npm ci
    - run: CI=false npm run build
    - name: Google Cloud Storage Setup
      uses: google-github-actions/setup-gcloud@master
      with:
        version: "290.0.0"
        project_id: ${{secrets.GCP_PROJECT_ID}}
        service_account_key: ${{secrets.GCP_SERVICE_ACCOUNT_KEY}}
        export_default_credentials: true
    - name: Deployment
      run: gsutil rsync -d -r dist gs://dev-import-chat.intospace.io
    
  